### ISSUE TITLE
Error installing via yay on Manjaro Linux

### ISSUE THREAD

**Issue by jamesray1** [OzymandiasTheGreat/emoji-keyboard#35] opened 2018-10-09 07:50 UTC
```bash
➜  ~  yay emoji-keyboard-git
==> Starting package()...
Failed to list sessions: Access denied
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from lib.emoji_shared import version
  File "/home/james/.cache/yay/emoji-keyboard-git/src/emoji-keyboard/lib/emoji_shared.py", line 102, in <module>
    wayland = check_wayland()
  File "/home/james/.cache/yay/emoji-keyboard-git/src/emoji-keyboard/lib/emoji_shared.py", line 87, in check_wayland
    ['loginctl', 'show-session', session, '-p', 'Type'],
UnboundLocalError: local variable 'session' referenced before assignment
==> ERROR: A failure occurred in package().
    Aborting...
Error making: emoji-keyboard-git
```
I thought that this might have something to do with just installing XFCE on the same partition as Gnome, but after removing XFCE again, the issue persisted. I have also been able to do a `yay` update.

System info (using X.Org not Wayland):
```bash
➜  ~ inxi -Fxz
System:    Host: james-dl Kernel: 4.14.71-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 
           Desktop: Gnome 3.30.0 Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Latitude E6410 v: 0001 serial: <filter> 
           Mobo: Dell model: 0HNGW4 serial: <filter> BIOS: Dell v: A16 date: 12/05/2013 
Battery:   ID-1: BAT0 charge: 48.8 Wh condition: 39.4/48.8 Wh (81%) model: Samsung SDI DELL PT43699 
           status: Full 
CPU:       Topology: Dual Core model: Intel Core i5 M 560 bits: 64 type: MT MCP arch: Nehalem rev: 5 
           L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21288 
           Speed: 1278 MHz min/max: 1199/2667 MHz Core speeds (MHz): 1: 2019 2: 1259 3: 1656 4: 1356 
Graphics:  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.1 driver: i915 resolution: 1440x900~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 18.2.2 direct render: Yes 
Audio:     Device-1: Intel 5 Series/3400 Series High Definition Audio driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Sound Server: ALSA v: k4.14.71-1-MANJARO 
Network:   Device-1: Intel 82577LM Gigabit Network driver: e1000e v: 3.2.6-k port: 7040 bus ID: 00:19.0 
           IF: eno1 state: down mac: <filter> 
           Device-2: Broadcom Limited BCM43224 802.11a/b/g/n driver: wl v: kernel port: 7000 bus ID: 02:00.0 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 1.20 TiB used: 513.87 GiB (41.8%) 
           ID-1: /dev/sda vendor: Seagate model: ST9320423AS size: 298.09 GiB 
           ID-2: /dev/sdb type: USB vendor: Seagate model: Expansion size: 931.51 GiB 
Partition: ID-1: / size: 105.24 GiB used: 67.01 GiB (63.7%) fs: ext4 dev: /dev/sda4 
Sensors:   System Temperatures: cpu: 46.0 C mobo: N/A sodimm: 43.0 C 
           Fan Speeds (RPM): cpu: 2880 
Info:      Processes: 205 Uptime: 2h 38m Memory: 3.72 GiB used: 2.50 GiB (67.1%) Init: systemd Compilers: 
           gcc: 8.2.1 Shell: zsh v: 5.6.2 inxi: 3.0.26
```
I can't install `pip3` via `pacman` or `yay` or find it on Octopi in the official or AUR repositories.

**Comment by rubenwardy** [comment] 2018-10-19 19:55
Duplicate of #31

**Comment by OzymandiasTheGreat** [comment] 2020-02-15 11:08
New version, no installation, it's an AppImage, use that.

**Closed by OzymandiasTheGreat** 2020-02-15 11:08 UTC
