### ISSUE TITLE
"On selecting emoji: Type" not working for me

### ISSUE THREAD

**Issue by istrasci** [OzymandiasTheGreat/emoji-keyboard#20] opened 2017-11-17 00:17 UTC
Does not insert emoji into the focused application.  I still have to paste it in.  Seems to do the same thing as "Copy".

##### Linux Mint 18.2 Mate Edition.

**Comment by skmkenn** [comment] 2017-11-17 16:57
I can confirm this as well -- clicking on an emoji does not insert it as mentioned regardless of what the keyboard options have been set to.

Previous release (2.1.0) does not exhibit this issue.

**System:** Linux Mint 18.2 MATE

**Comment by OzymandiasTheGreat** [comment] 2017-11-24 08:34
My bad, I rushed with the release without properly testing and updating readme.
Short version: this is a permission issue. Python-evdev (which emoji-keyboard uses to emulate keypress) needs write access to `/dev/uinput` which is owned by root (it wasn't for some reason on my dev system).
To fix that you need to create a uinput group, add yourself to that group and write a udev rule then reboot.
Your udev rule should look like this:
```KERNEL=="uinput", GROUP="uinput", MODE="0660"```

Long version:
Emulating keypresses under X was relatively simple and did not require any extra permissions, but since most major distros have switched to Wayland those methods don't work anymore. In my rush to add Wayland support and because my dev system was borked I failed to realize how troublesome this is gonna be for people still on X. In the next version if you're still on X you'll be able to install python-xlib as an optional dependency to have full functionality without messing with permissions. For now (or if you're on wayland) creating udev rule is the only way. You can also refrain from updating until next release.
Talking about next release, it's gonna take a bit, since I'm quite busy right now. Apologies.

**Comment by OzymandiasTheGreat** [comment] 2017-12-30 08:39
This is fixed in the latest release (2.3.0), you might have to install `python-xlib` separately.
The README has also been updated with relevant info.

**Comment by OzymandiasTheGreat** [comment] 2018-07-06 03:11
Isn't Fedora using Wayland? If so, you need to python3-evdev and allow access to input device or run as root. Yes, this sucks but Wayland blocks access to input for applications run as regular users so for emulating paste we need either root or permission change.

**Comment by mr** [comment] 2018-07-06 11:06
I'm using X on Fedora.

**Comment by OzymandiasTheGreat** [comment] 2018-07-07 00:44
Ok, I'm lost then. When running from terminal do you get any errors?

**Comment by mr** [comment] 2018-07-07 16:01
Looks like it required either a reboot or log out/log in. It's working now.

**Comment by OzymandiasTheGreat** [comment] 2018-07-08 00:57
That's strange, but I'm glad it works!

**Closed** 2020-02-15 11:21 UTC
