### ISSUE TITLE
When clicking an emoji, it just pasted whatever's in the clipboard

### ISSUE THREAD

**Issue by sahmes** [OzymandiasTheGreat/emoji-keyboard#6] opened 2017-04-29 22:56 UTC
On Kubuntu 14.04, installed both from source and from Debian package, both have the same effect. Choosing any emoji has the same effect as Ctrl+V, whatever was in the clipboard before is pasted to where the cursor is.

**Comment by OzymandiasTheGreat** [comment] 2017-04-30 07:01
Pushed (hopefully) a fix just now, could you try the latest commit and see if it works?

**Comment by sahmes** [comment] 2017-04-30 07:19
Thanks for the quick response, unfortunately the problem still exists. Earlier, when I clicked an emoji, the text from the clipboard would appear immediately, now it seems there is a short delay. Also strangely when I try to add an emoji in a Firefox window, now nothing happens, while in any other program (GTK or QT) I get the clipboard content pasted. Earlier, Firefox functioned like any other program. See attached errors when starting the keyboard from the terminal. Lines 1-333 are printed at startup, lines 340 to 1003 are printed when I try to insert an emoji to a GTK application.
[emoji-error.txt](https://github.com/OzymandiasTheGreat/emoji-keyboard/files/966603/emoji-error.txt)

**Comment by OzymandiasTheGreat** [comment] 2017-04-30 07:30
Okay, this one is because emoji-keyboard requires python 3.5. Any chance you can get python 3.5 running and see if it solves the issues?

**Comment by OzymandiasTheGreat** [comment] 2017-04-30 07:45
Did some testing and those should not be related to pasting emoji. In fact, everything except sorting of recent emoji should work on earlier versions of python.
Back to the pasting bug, added another timeout, can you try the latest commit?

**Comment by sahmes** [comment] 2017-04-30 08:00
Sorry, the problem persisted with the last commit with Python 3.4... I tried Python 3.5 briefly but there was some problem up the dependency tree (with gi), somehow pip didn't get a good version of it, so I was not able to test the emoji keyboard with it.

**Comment by OzymandiasTheGreat** [comment] 2017-04-30 08:07
Hmm, I can't reproduce this at all. Anyway, made the timeouts ridiculous, could you try it again? If it doesn't work now I'm afraid I'm out of ideas.

**Comment by sahmes** [comment] 2017-04-30 08:20
It didn't solve the problem unfortunately. There is a ~3 second delay now between clicking an emoji and getting the clipboard's content pasted in the window. Maybe I'll give Python 3.5 another go later.

**Comment by sahmes** [comment] 2017-04-30 18:59
I tried Python 3.6; was not easy to figure out how to install the correct version of gi, but I did eventually. Unfortunately exactly the same as before 😞 there are no errors printed out at all.

Moreover, now the there seems to be some problem with the rendering, this is how it looks like on my screen:

![emojis](https://cloud.githubusercontent.com/assets/10907333/25567149/cd5832b8-2de7-11e7-8e2e-713d845b661d.png)

**Comment by OzymandiasTheGreat** [comment] 2017-05-01 05:43
Rendering's on gi and Gtk, I'm afraid there's nothing I can do about.
As for pasting, I'm downloading Kubuntu to see if it's something specific to your system or if it's just Gtk not playing nice with KDE.

**Comment by OzymandiasTheGreat** [comment] 2017-05-01 11:50
Finally managed to reproduce this, not working on KDE at all. I'll try switching from Gtk to Xlib for clipboard access and see if that works.

**Comment by sahmes** [comment] 2017-05-01 12:03
Thanks :) Kubuntu 14.04 has some glitches with recent versions of Firefox seemingly due to the newer version of GTK, while Kubuntu 16.04 renders everything normally, maybe it's related to either the pasting bug or the bad rendering.

**Comment by OzymandiasTheGreat** [comment] 2017-05-04 12:01
So finally got some testing done and I got bad news. Python-xlib doesn't play nice with KDE either, which leads me to believe there're some non-standard behaviors in KDE. One thing that immediately popped out was clipboard manager randomly taking over, but I guess there's more.
So in summary fixing this would require rewriting the app in qt and I have no desire or time to learn qt, sorry, marking this as won't fix.

**Comment by billwanjohi** [comment] 2017-05-10 03:17
I'm experiencing the same in i3 window manager. Can I suggest that you update the readme to indicate only GTK-based desktop environments are supported?

**Comment by OzymandiasTheGreat** [comment] 2017-05-10 12:58
@sahmes , @billwanjohi Okay, I think I figured it out. Could both of you try out the latest commit and see how it works? Note that at least under KDE you need `python-xlib` version 0.19 which is only available through pip, so update that as well. I also introduced a new bug somehow, where exiting through indicator menu doesn't work, but sending SIGTERM works properly. I'll have to figure this out later.

**Comment by sahmes** [comment] 2017-05-13 15:42
Yep, the clipboard problem is resolved on Kubuntu 14.04 using Python 3.6 and Xlib 0.19 🙂

The hideous SVG distortion is still there though 😞
I really couldn't figure out how to install a fresh gi; version 1.2 [here](https://pypi.python.org/pypi/gi/) (same thing I get via pip) is actually not compatible with python 3. When installing `python3-gi` via apt, it goes to the (default) Python 3.4 path in my system, I manually linked it into the dist-packages of 3.6 installation, it kinda works but may be the cause of the problem.
```
me@myserver:~$ python3.4 -c "import gi; print(gi.__version__)"
3.12.0
````
Where can I find the source for this "3.12" version? Maybe it's a completely different package?

**Comment by OzymandiasTheGreat** [comment] 2017-05-13 18:33
@sahmes Good to hear it works!
As for the rendering glitches, I'm sorry, this is over my head. No idea where to even start with this.

**Comment by billwanjohi** [comment] 2017-07-06 16:04
@OzymandiasTheGreat rebuilding after your changes fixed my problems.

**Closed** 2017-08-21 18:00 UTC
Labels: bug
