### ISSUE TITLE
JavaScript Error at first startup.

### ISSUE THREAD

**Issue by aakashsinghbais** [OzymandiasTheGreat/emoji-keyboard#57] opened 2020-04-28 13:32 UTC
At startup, I encountered this error:
![error](https://user-images.githubusercontent.com/56718090/80493191-b5f97600-8982-11ea-8672-5e00503171e2.png)
Immediately after the first, there was a second one:
![image](https://user-images.githubusercontent.com/56718090/80494137-f3123800-8983-11ea-89c8-e9777fcfdd96.png)
...and on selecting an emoji, the app encountered a third one:
![image](https://user-images.githubusercontent.com/56718090/80494264-1a690500-8984-11ea-9753-6e3f6005f5bc.png)
(which apparently is the same as the second one).

---
OS: Ubuntu 20.04LTS

**Comment by foben** [comment] 2020-05-02 11:14
I have the exact same issue with `emoji-keyboard-3.0.0-rc2.AppImage`.
When I start the AppImage I get the first two errors. Hitting ctrl+super+Space opens the Dialog, but upon clicking an emoji I get the third error as well.

OS: Arch

**Comment by csamu** [comment] 2020-08-27 11:55
I got the same error with rc2. 
The following in `python.log`:

2020-08-27T11:45:30.169Z - "Traceback (most recent call last):"
2020-08-27T11:45:30.169Z - "  File \"/usr/lib/python3.8/runpy.py\", line 193, in _run_module_as_main"
2020-08-27T11:45:30.169Z - "    return _run_code(code, main_globals, None,"
2020-08-27T11:45:30.169Z - "  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code"
2020-08-27T11:45:30.169Z - "    exec(code, run_globals)"
2020-08-27T11:45:30.169Z - "  File \"/tmp/.mount_emoji-2kmM6F/resources/main.pyz/__main__.py\", line 3, in <module>"
2020-08-27T11:45:30.169Z - "  File \"/tmp/.mount_emoji-2kmM6F/resources/main.pyz/_bootstrap/__init__.py\", line 182, in bootstrap"
2020-08-27T11:45:30.169Z - "  File \"/tmp/.mount_emoji-2kmM6F/resources/main.pyz/_bootstrap/__init__.py\", line 33, in run"
2020-08-27T11:45:30.169Z - "  File \"/usr/lib/python3.8/runpy.py\", line 262, in run_path"
2020-08-27T11:45:30.169Z - "    code, fname = _get_code_from_file(run_name, path_name)"
2020-08-27T11:45:30.169Z - "  File \"/usr/lib/python3.8/runpy.py\", line 232, in _get_code_from_file"
2020-08-27T11:45:30.169Z - "    with io.open_code(fname) as f:"
2020-08-27T11:45:30.169Z - "TypeError: open_code() argument 'path' must be str, not PosixPath"
2020-08-27T11:45:30.171Z - Error: TypeError: open_code() argument 'path' must be str, not PosixPath

This was also in the terminal:

(AppImageLauncher:289974): GLib-**CRITICAL** **: 13:44:15.330: g_file_test: assertion 'filename != NULL' failed

**Comment by federicotorrielli** [comment] 2020-09-12 09:52
Same here on Pop! 20.04

**Comment by OzymandiasTheGreat** [comment] 2020-10-27 05:17
Sorry for the (very) late reply.
This is caused by Python 3.8 bug/regression that I reported upstream and has been fixed for a while now, same as #54 .
Seems like your distributions have been using outdated Python without the fix, hence the error.
As this is fixed and latest version of Ubuntu includes recent enough version of Python, I'm closing this.

**Closed by OzymandiasTheGreat** 2020-10-27 05:17 UTC
