### ISSUE TITLE
Emoji-keyboard fails to start

### ISSUE THREAD

**Issue by WhyNotHugo** [OzymandiasTheGreat/emoji-keyboard#53] opened 2020-02-19 12:36 UTC
`emoji-keyboard` fails to start; it doesn't recognise one of the emoji files included:

```
$ emoji-keyboard 
Lockfile found but the process is not running.
Lockfile removed
Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 22, in <module>
    shared.emoji = egtk.Emoji()
  File "/usr/lib/python3.8/site-packages/emoji_keyboard/emoji_gtk.py", line 128, in __init__
    model = self.load_emoji()
  File "/usr/lib/python3.8/site-packages/emoji_keyboard/emoji_gtk.py", line 175, in load_emoji
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognise the image file format for file “/usr/lib/python3.8/site-packages/emoji_keyboard/data/emojitwo/1f600.svg” (3)
```

Any hints as to how I can debug this?

**Comment by OzymandiasTheGreat** [comment] 2020-02-19 19:21
Uh, looks like file got corrupted. Either that or another gtk bug.
My suggestion is you download the latest version AppImage and don't bother with this.
The old python/gtk version is no longer supported.

**Comment by WhyNotHugo** [comment] 2020-02-21 09:29
I'm using 2.3.0. Do you mean v3.0.0rc0? That doesn't seem to be packaged for my distro, I'll see if I can give that a go.

**Comment by WhyNotHugo** [comment] 2020-02-21 09:49
Crashed on startup:

![2020-02-21T10:46:19,990959522+01:00](https://user-images.githubusercontent.com/730811/75023086-810b0780-5497-11ea-9b94-159a56e9df39.png)

Got these popups with the stracktrace. I think you'll probably want to switch this to just printing to stdout like any normal app, no point in creating a window for an error if I can just see it in the console.

![2020-02-21T10:46:07,362948546+01:00](https://user-images.githubusercontent.com/730811/75023142-9da73f80-5497-11ea-82cd-d06504c84c7b.png)
![2020-02-21T10:46:10,651228874+01:00](https://user-images.githubusercontent.com/730811/75023150-9e3fd600-5497-11ea-87cd-3febb731ac84.png)
![2020-02-21T10:46:11,606530986+01:00](https://user-images.githubusercontent.com/730811/75023152-9ed86c80-5497-11ea-8c85-480e9cc967fc.png)
![2020-02-21T10:46:12,349943395+01:00](https://user-images.githubusercontent.com/730811/75023154-9ed86c80-5497-11ea-99d9-90ff5d311a1e.png)
![2020-02-21T10:46:13,056398541+01:00](https://user-images.githubusercontent.com/730811/75023156-9f710300-5497-11ea-83bc-2c1deb9ff561.png)
![2020-02-21T10:46:13,755220978+01:00](https://user-images.githubusercontent.com/730811/75023157-a0099980-5497-11ea-9748-8a4f5ca60e86.png)
![2020-02-21T10:46:14,465532914+01:00](https://user-images.githubusercontent.com/730811/75023159-a0099980-5497-11ea-96d3-3dcdb0e815a1.png)
![2020-02-21T10:46:15,144623705+01:00](https://user-images.githubusercontent.com/730811/75023160-a0a23000-5497-11ea-8d20-66eee353052d.png)
![2020-02-21T10:46:15,873022125+01:00](https://user-images.githubusercontent.com/730811/75023162-a0a23000-5497-11ea-9be1-0884aaddb6cf.png)
![2020-02-21T10:46:16,583884160+01:00](https://user-images.githubusercontent.com/730811/75023163-a13ac680-5497-11ea-94f5-cfb7bf923331.png)
![2020-02-21T10:46:17,268291360+01:00](https://user-images.githubusercontent.com/730811/75023164-a13ac680-5497-11ea-9976-5a49089239f0.png)
![2020-02-21T10:46:17,931602132+01:00](https://user-images.githubusercontent.com/730811/75023165-a1d35d00-5497-11ea-92bd-da648bf346c4.png)
![2020-02-21T10:46:18,652010605+01:00](https://user-images.githubusercontent.com/730811/75023166-a26bf380-5497-11ea-8ed7-c4658d7c90ad.png)
![2020-02-21T10:46:19,302266950+01:00](https://user-images.githubusercontent.com/730811/75023169-a3048a00-5497-11ea-9449-7f43ca0fd29a.png)

**Comment by BunnyTheLifeguard** [comment] 2020-03-11 22:54
Got the same errors with the most recent release.

**Comment by TassiloBalbo** [comment] 2020-03-29 15:11
> Got the same errors with the most recent release plus this one after the last one:
> 
> ![Screenshot_20200311_235810](https://user-images.githubusercontent.com/36411819/76471909-4a6c4100-63f4-11ea-87c3-c578cec7dd17.png)
> 
> Interestingly enough, the icon appears in my taskbar after that (can't resize the keyboard tho), but when selecting an emoji, it crashes with the same error message.

I have the same problem too.

**Comment by OzymandiasTheGreat** [comment] 2020-04-17 15:01
@WhyNotHugo , @BunnyTheLifeguard , @TassiloBalbo 
First, sorry for the late reply, been out with particularly bad flu for almost 2 months.
As for the error windows, that shouldn't have made it to release. At least I made it a release candidate.

On to the main issue, this is a [python 3.8 bug/regression](https://bugs.python.org/issue39517).
It's fixed by now, but it doesn't seem the fix made it to release yet. One solution would be to use python 3.7 for now. Another - just wait a bit longer and it will start working on it's own.

**Closed** 2020-10-27 05:11 UTC
Labels: wontfix
