### ISSUE TITLE
AppImage crashes on launch (Javascript error)

### ISSUE THREAD

**Issue by joyeusenoelle** [OzymandiasTheGreat/emoji-keyboard#54] opened 2020-02-20 03:25 UTC
Running Pop! OS 18.04, based on Ubuntu 18.04 with Gnome as window manager. 

Both 3.0.0rc0 and 3.0.0rc1 appimages crash with the same error:

**A JavaScript error occurred in the main process**

```Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from src/assets/icons/icon-dark-48.png
    at lpcMainImpl.<anonymous> (/tmp/.mount_emoji-ACLzo3/resources/app.asar/main.js:146:15
    at lpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3839:15)
    at WebContents.emit (events.js:210:5)
```

This error persists after reboot.

**Comment by OzymandiasTheGreat** [comment] 2020-02-20 04:13
Huh, I have no clue 'bout this one to be honest.
I'll look into it over the weekend.

**Comment by gadicc** [comment] 2020-02-20 05:01
@joyeusenoelle, is that the only error you get?

I'm also trying out the v3 rc's.  I get a similar error to the above but also a few other things:

```
Uncaught exception!!!     (*after every line below)
"Traceback (most recent call last):"
"  File \"/usr/lib/python3.8/runpy.py\", line 193, in _run_module_as_main"
"    return _run_code(code, main_globals, None,"
"  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code"
"    exec(code, run_globals)"
"  File \"/tmp/.mount_emoji-AcPWoe/resources/main.pyz/__main__.py\", line 3, in <module>"
"  File \"/tmp/.mount_emoji-AcPWoe/resources/main.pyz/_bootstrap/__init__.py\", line 182, in bootstrap"
"  File \"/tmp/.mount_emoji-AcPWoe/resources/main.pyz/_bootstrap/__init__.py\", line 33, in run"
"  File \"/usr/lib/python3.8/runpy.py\", line 262, in run_path"
"    code, fname = _get_code_from_file(run_name, path_name)"
"  File \"/usr/lib/python3.8/runpy.py\", line 232, in _get_code_from_file"
"    with io.open_code(fname) as f:"
"TypeError: open_code() argument 'path' must be str, not PosixPath"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:925131) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from src/assets/icons/icon-dark-48.png
    at IpcMainImpl.<anonymous> (/tmp/.mount_emoji-AcPWoe/resources/app.asar/main.js:146:15)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3839:15)
    at WebContents.emit (events.js:210:5)
    at Object.showErrorBox (electron/js2c/browser_init.js:994:20)
    at electron/js2c/browser_init.js:5654:16
(node:925131) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from src/assets/icons/icon-dark-48.png
    at IpcMainImpl.<anonymous> (/tmp/.mount_emoji-AcPWoe/resources/app.asar/main.js:146:15)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3839:15)
    at WebContents.emit (events.js:210:5)
    at Object.showErrorBox (electron/js2c/browser_init.js:994:20)
    at electron/js2c/browser_init.js:5654:16
(node:925131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:925131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:925131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:925131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like I also get the conversion error for `src/assets/icons/icon-dark-48.png`, not sure if it's that image specific or if that's just the first one it tries to convert.

I guess `TypeError: open_code() argument 'path' must be str, not PosixPath` could be the other important issue.

Could there be anything in a newly created `.config/emoji-keyboard` that relates to this?

Excited for this new release!  Thanks for all the time you've put into it so far :D

**Comment by joyeusenoelle** [comment] 2020-02-20 05:03
I'm running the AppImage as an executable within Gnome, and the error message presented is the only one I get. If there are other errors, I don't see them and they don't show up in my logs.

**Comment by OzymandiasTheGreat** [comment] 2020-02-20 05:09
Oh that makes more sense. There's  a python bug I actually filled and clearly forgot to work around it...
Anyway won't have much time until the weekend.
Thank you for your patience.

**Comment by twinklebob** [comment] 2020-03-09 16:36
Is there any update on this one? Anything anyone else can do to help?

**Comment by OzymandiasTheGreat** [comment] 2020-03-09 16:45
I'm terribly sorry, I've been out with the flu for 2 weeks now, I'll get on it as soon as I get better.

**Comment by twinklebob** [comment] 2020-03-09 16:53
No worries, thanks for the update. I'm looking forward to giving the emoji
keyboard a go once it's ready!

**Comment by OzymandiasTheGreat** [comment] 2020-04-17 05:41
Alright, I'm mostly back. Here goes:
- @joyeusenoelle This was caused by relative path that became invalid after packaging. It is fixed in v3.0.0rc2.
  - This however isn't a critical bug, so it shouldn't crash because of it. If you still experience crashes, try running AppImage from command line and checking `~/.config/emoji-keyboard/python.log` for additional errors.
- @gadicc  This is a python [3.8 bug/regression](https://bugs.python.org/issue39517). Best you can do is is upgrade python point release since it seems fixed by now or downgrade to python 3.7.
- @twinklebob Look at first point. Please try the new version and see if you experience any additional errors.

**Comment by gadicc** [comment] 2020-04-17 07:22
@OzymandiasTheGreat thanks for the update!  The latest `python` offered by my distribution doesn't seem to have this fixed yet, will keep an eye on it.  Thank you.

**Comment by twinklebob** [comment] 2020-04-17 10:29
@OzymandiasTheGreat Works great, thanks. Is there supposed to be an icon in the tray for it? I can get to it fine from the keyboard shortcuts, but there's no sign the app is running.

**Comment by OzymandiasTheGreat** [comment] 2020-04-17 14:53
@twinklebob Yes, you should see a happy poop emoji in the tray.
During development electron would occasionally throw Gtk-related warning and the icon wouldn't show up then. However a restart would always fix this and this happened very sporadically so I just ignored it.
Basically, does the icon appear on restart? If not, do you see any warnings on the command line?

**Comment by twinklebob** [comment] 2020-04-20 09:58
@OzymandiasTheGreat strange, I'm not seeing the icon in the tray. I'm running Cinnamon on Linux Mint, so maybe there's a slight difference in the way the tray icons are registered. It's not a big deal, I can still use it with the keyboard shortcuts, but do you want me to raise a new issue for it anyway?

**Comment by OzymandiasTheGreat** [comment] 2020-10-27 05:01
@twinklebob I'm so sorry, I've been busy with my day job and completely forgot about this issue.
If you're still not seeing the tray icon on the latest versions of your OS (assuming you're still using this 😅)
please open a separate issue.
For now, I'm closing this issue, as the crashes seem resolved.

**Closed by OzymandiasTheGreat** 2020-10-27 05:01 UTC
