### ISSUE TITLE
Search performance is slow in Search or Search emoji form

### ISSUE THREAD

**Issue by orsonteodoro** [OzymandiasTheGreat/emoji-keyboard#24] opened 2018-01-08 22:36 UTC
As I type a letter a letter in the input box, it causes a noticeable slow down and not snappy at all.  Consider limiting results returned.  Also, if you type a letter, the letter from the Regional Indicator Symbol (https://en.wikipedia.org/wiki/Regional_Indicator_Symbol) is not at the top of the list.

**Comment by OzymandiasTheGreat** [comment] 2018-01-09 04:05
Oh this is two bugs
Can't reproduce the slow down, on my machine suggestions appear instantly. Test VMs also perform well with considerably less resources. Do you get any errors when running in terminal?
Country codes should work as shortnames (e.g. :lt:), alas I just tested and they don't. Shouldn't be hard to fix tho.

**Comment by skielred** [comment] 2019-03-15 10:02
I have very big performance issues too. When running from terminal, the only error showing is this (and it shows only once at start): `(emoji-keyboard:5281): Gdk-CRITICAL **: 10:56:58.362: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`.

I have instant results if I use the shortcodes (:emoji:) but when directly searching for text without the colons, it takes a while before updating results and showing the characters I type. I can type full words before the search bar actually showing anything!

I'll get use to shortcodes for now but if the slow results on regular searches can be fixed I'd be glad!

I use Fedora 29 and I run emoji-keyboard from i3, using the latest (afe17aa) GitHub master branch.

**Comment by OzymandiasTheGreat** [comment] 2020-02-15 11:20
So this was most likely gtk bugs, but that's no longer applicable since emoji-keyboard is now an electron app!
Please try the new version.
I'm closing this.

**Closed by OzymandiasTheGreat** 2020-02-15 11:20 UTC
